### ISSUE TITLE
[1.14 Pre-Release 4] MixinTextFieldWidget Crash when opening inventory or attempting to hover over Shulker Box

### ISSUE THREAD

**Issue by insanj** [MisterPeModder/ShulkerBoxTooltip#1]
Not compatible with latest snapshot due to mapping changes. Will look into potential fixes myself in a fork if I'm lucky. Full log:

```
Mixin apply failed clothconfig.mixins.json:MixinTextFieldWidget -> net.minecraft.class_342: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Shadow field field_2090 was not located in the target class net.minecraft.class_342. Using refmap ClothConfig-refmap.json org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Shadow field field_2090 was not located in the target class net.minecraft.class_342. Using refmap ClothConfig-refmap.json at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:563) at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:263) at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:241) at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1144) at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:267) at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353) at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724) at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703) at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509) at net.fabricmc.loader.launch.knot.KnotClassDelegate.transform(KnotClassDelegate.java:151) at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:173) at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:130) at java.lang.ClassLoader.loadClass(ClassLoader.java:357) at net.minecraft.class_309.method_1466(class_309.java:389) at net.minecraft.class_309$$Lambda$1570/1821783147.invoke(Unknown Source) at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37) at org.lwjgl.system.JNI.invokeV(Native Method) at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3050) at com.mojang.blaze3d.platform.GLX.pollEvents(GLX.java:223) at net.minecraft.class_310.method_1523(class_310.java:926) at net.minecraft.class_310.method_1514(class_310.java:410) at net.minecraft.client.main.Main.main(Main.java:154) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:497) at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:130) at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
```

Followed by:
```
[STDERR]: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [clothconfig.mixins.json:MixinTextFieldWidget] from phase [DEFAULT] in config [clothconfig.mixins.json] FAILED during APPLY
...
[STDERR]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Shadow field field_2090 was not located in the target class net.minecraft.class_342. Using refmap ClothConfig-refmap.json
...
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [clothconfig.mixins.json:MixinTextFieldWidget] from phase [DEFAULT] in config [clothconfig.mixins.json] FAILED during APPLY
 ```

**Comment by MisterPeModder** [comment]
Wait, pre release 4 is a thing?

Edit:
it is, mojang is fast it seems...

**Comment by insanj** [comment]
@MisterPeModder Yep! Looks like this issue is related to the Cloth config API

**Comment by MisterPeModder** [comment]
Open an issue on cloth

**Comment by MisterPeModder** [comment]
Il look into it and submit a pr if I can find the issue.

**Comment by insanj** [comment]
@MisterPeModder Not really sure if that's the issue, was just a suspicion from the crash log. If anything I imagine updating to the latest version will fix it since you're on 0.1.2 instead of 0.1.3

**Comment by insanj** [comment]
(They updated it merely hours ago: https://minecraft.curseforge.com/projects/cloth-config?gameCategorySlug=mc-mods&projectID=319057)

**Comment by MisterPeModder** [comment]
While i'm updating (loom is veery slow), you can download cloth-config from curseforge and put it in your mods folder. It should replace the builtin version and (might) work
