### ISSUE TITLE
Crash with shulkerboxtooltip-1.4.3+1.15.0

### ISSUE THREAD

**Issue by Heitzenberg** [MisterPeModder/ShulkerBoxTooltip#10]
---- Minecraft Crash Report ----
// Don't do that.

Time: 11.12.19 11:26
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:55)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:34)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.<init>(class_310.java:391)
	at net.minecraft.client.main.Main.main(Main.java:164)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	Suppressed: java.lang.NoClassDefFoundError: me/sargunvohra/mcmods/autoconfig1u/ConfigData
		at java.base/java.lang.ClassLoader.defineClass1(Native Method)
		at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
		at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151)
		at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:156)
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
		at com.misterpemodder.shulkerboxtooltip.impl.ShulkerBoxTooltip.onInitializeClient(ShulkerBoxTooltip.java:50)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:48)
		... 11 more
	Caused by: java.lang.ClassNotFoundException: me.sargunvohra.mcmods.autoconfig1u.ConfigData
		at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
		at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
		at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161)
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
		... 18 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:55)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:34)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.<init>(class_310.java:391)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:164)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.15
	Minecraft Version ID: 1.15
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 13.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 648285152 bytes (618 MB) / 838860800 bytes (800 MB) up to 3221225472 bytes (3072 MB)
	CPUs: 12
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:ParallelGCThreads=6 -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	Launched Version: fabric-loader-0.7.2+build.174-1.15
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>

**Comment by MisterPeModder** [comment]
Can you share the whole log?

**Comment by Heitzenberg** [comment]
That was the whole crash report. The log file is:

[12:30:47] [main/INFO]: Loading for game Minecraft 1.15
[12:30:49] [main/INFO]: [FabricLoader] Loading 5 mods: minecraft@1.15, fabric-resource-loader-v0@0.1.9+f3d8141be4, fabricloader@0.7.2+build.174, shulkerboxtooltip@1.4.3+1.15.0, cloth-config2@2.4-unstable.201911031154
[12:30:49] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/C:/Users/xxx/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.8+build.16/sponge-mixin-0.8+build.16.jar Service=Knot/Fabric Env=CLIENT
[12:30:50] [main/INFO]: Setting user: Heitzenberg

**Comment by MisterPeModder** [comment]
I think I know what the issue is, for the time being download fabric-api and put it in the mods folders

**Comment by Heitzenberg** [comment]
Okay, thanks in advance for fixing it! :)

**Comment by Heitzenberg** [comment]
If I understand the changelog for 1.4.4 correctly, FabricAPI will now always be required, correct?

**Comment by MisterPeModder** [comment]
Yes, the bundled fabric API was causing incompatibility issues with other mods.

**Comment by mazunki** [comment]
Can you update the description of the mod to say Fabric-API is a dependency? I got the same error in 1.15.2, and this issue solved it. I don't think most people will search in closed issues.
