### ISSUE TITLE
Server ran into this error in latest version.

### ISSUE THREAD

**Issue by KofiFS** [MisterPeModder/ShulkerBoxTooltip#100]
#### Issue Description:

Delete this line after reading it: If this bug occurs in a modpack, please report this to the modpack author first.

#### Steps to reproduce: Run on a server

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"):

- ShulkerBoxTooltip: shulkerboxtooltip-forge-3.2.0+1.19.2.jar
- Minecraft: Forge - 43.1.47
- Fabric Loader: NA
- Fabric API: NA
- Other mods (if relevant): Using OREKU Modpack

#### Your most recent log file where the issue was present: 
[22.10 12:20:46] [Server] ---------------------------------------------------------------------------------------
[22.10 12:20:46] [Server] -- Head --
[22.10 12:20:46] [Server] Threadmain
[22.10 12:20:46] [Server] Stacktrace:
[22.10 12:20:46] [Server] 	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.19.2-43.1.47.jar%2367!/:1.{}
[22.10 12:20:46] [Server] -- MOD shulkerboxtooltip --
[22.10 12:20:46] [Server] Details:
[22.10 12:20:46] [Server] 	Mod File/mods/shulkerboxtooltip-forge-3.2.0+1.19.2.jar
[22.10 12:20:46] [Server] 	Failure messageShulkerBoxTooltip (shulkerboxtooltip) has failed to load correctly
[22.10 12:20:46] [Server] 		java.lang.RuntimeExceptionAttempted to load class com/misterpemodder/shulkerboxtooltip/api/color/ColorRegistry for invalid dist DEDICATED_SERVER
[22.10 12:20:46] [Server] 	Mod Version3.2.0+1.19.2
[22.10 12:20:46] [Server] 	Mod Issue URLhttps://github.com/MisterPeModder/ShulkerBoxTooltip/issues
[22.10 12:20:46] [Server] 	Exception messagejava.lang.RuntimeException: Attempted to load class com/misterpemodder/shulkerboxtooltip/api/color/ColorRegistry for invalid dist DEDICATED_SERVER
[22.10 12:20:46] [Server] Stacktrace:
[22.10 12:20:46] [Server] 	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.19.2-43.1.47.jar%2367!/:1.{}
[22.10 12:20:46] [Server] 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.8.jar%2354!/:?] {}
[22.10 12:20:46] [Server] 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.8.jar%2354!/:?] {}
[22.10 12:20:46] [Server] 	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar%2354!/:?] {}
[22.10 12:20:46] [Server] 	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.4.jar:?] {}
[22.10 12:20:46] [Server] 	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] {}
[22.10 12:20:46] [Server] 	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?] {}
[22.10 12:20:46] [Server] 	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] {}
[22.10 12:20:46] [Server] 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?] {}
[22.10 12:20:46] [Server] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
[22.10 12:20:46] [Server] 	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?] {re:mixin}
[22.10 12:20:46] [Server] 	at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?] {re:mixin}
[22.10 12:20:46] [Server] 	at java.lang.Class.privateGetPublicMethods(Class.java:3427) ~[?:?] {re:mixin}
[22.10 12:20:46] [Server] 	at java.lang.Class.privateGetPublicMethods(Class.java:3433) ~[?:?] {re:mixin}
[22.10 12:20:46] [Server] 	at java.lang.Class.getMethods(Class.java:2019) ~[?:?] {re:mixin}
[22.10 12:20:46] [Server] 	at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:83) ~[eventbus-6.0.3.jar%2351!/:?] {}
[22.10 12:20:46] [Server] 	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:126) ~[eventbus-6.0.3.jar%2351!/:?] {}
[22.10 12:20:46] [Server] 	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:61) ~[javafmllanguage-1.19.2-43.1.47.jar%23235!/:?] {}
[22.10 12:20:46] [Server] 	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:mixin}
[22.10 12:20:46] [Server] 	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:48) ~[javafmllanguage-1.19.2-43.1.47.jar%23235!/:?] {}
[22.10 12:20:46] [Server] 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:78) ~[javafmllanguage-1.19.2-43.1.47.jar%23235!/:?] {}
[22.10 12:20:46] [Server] 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.1.47.jar%23234!/:?] {}
[22.10 12:20:46] [Server] 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
[22.10 12:20:46] [Server] 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
[22.10 12:20:46] [Server] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
[22.10 12:20:46] [Server] 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
[22.10 12:20:46] [Server] 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
[22.10 12:20:46] [Server] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
[22.10 12:20:46] [Server] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
[22.10 12:20:46] [Server] -- System Details --
[22.10 12:20:46] [Server] Details:
[22.10 12:20:46] [Server] 	Minecraft Version1.19.2
[22.10 12:20:46] [Server] 	Minecraft Version ID1.19.2
[22.10 12:20:46] [Server] 	Operating SystemLinux (amd64) version 4.15.0-189-generic
[22.10 12:20:46] [Server] 	Java Version17.0.1, Oracle Corporation
[22.10 12:20:46] [Server] 	Java VM VersionJava HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
[22.10 12:20:46] [Server] 	Memory1367589392 bytes (1304 MiB) / 1761607680 bytes (1680 MiB) up to 12884901888 bytes (12288 MiB)
[22.10 12:20:46] [Server] 	CPUs32
[22.10 12:20:46] [Server] 	Processor VendorGenuineIntel
[22.10 12:20:46] [Server] 	Processor NameIntel(R) Xeon(R) CPU E5-2667 v4 @ 3.20GHz
[22.10 12:20:46] [Server] 	IdentifierIntel64 Family 6 Model 79 Stepping 1
[22.10 12:20:46] [Server] 	MicroarchitectureBroadwell (Server)
[22.10 12:20:46] [Server] 	Frequency (GHz)3.20
[22.10 12:20:46] [Server] 	Number of physical packages2
[22.10 12:20:46] [Server] 	Number of physical CPUs16
[22.10 12:20:46] [Server] 	Number of logical CPUs32
[22.10 12:20:46] [Server] 	Graphics card #name: ASPEED Graphics Family
[22.10 12:20:46] [Server] 	Graphics card #vendor: ASPEED Technology, Inc. (0x1a03)
[22.10 12:20:46] [Server] 	Graphics card #VRAM (MB): 0.00
[22.10 12:20:46] [Server] 	Graphics card #deviceId: 0x2000
[22.10 12:20:46] [Server] 	Graphics card #versionInfo: unknown
[22.10 12:20:46] [Server] 	Virtual memory max (MB)174694.83[22.10 12:20:46] [Server] ---------------------------------------------------------------------------------------
[22.10 12:20:46] [Server] -- Head --
[22.10 12:20:46] [Server] Threadmain
[22.10 12:20:46] [Server] Stacktrace:
[22.10 12:20:46] [Server] 	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.19.2-43.1.47.jar%2367!/:1.{}
[22.10 12:20:46] [Server] -- MOD shulkerboxtooltip --
[22.10 12:20:46] [Server] Details:
[22.10 12:20:46] [Server] 	Mod File/mods/shulkerboxtooltip-forge-3.2.0+1.19.2.jar
[22.10 12:20:46] [Server] 	Failure messageShulkerBoxTooltip (shulkerboxtooltip) has failed to load correctly
[22.10 12:20:46] [Server] 		java.lang.RuntimeExceptionAttempted to load class com/misterpemodder/shulkerboxtooltip/api/color/ColorRegistry for invalid dist DEDICATED_SERVER
[22.10 12:20:46] [Server] 	Mod Version3.2.0+1.19.2
[22.10 12:20:46] [Server] 	Mod Issue URLhttps://github.com/MisterPeModder/ShulkerBoxTooltip/issues
[22.10 12:20:46] [Server] 	Exception messagejava.lang.RuntimeException: Attempted to load class com/misterpemodder/shulkerboxtooltip/api/color/ColorRegistry for invalid dist DEDICATED_SERVER
[22.10 12:20:46] [Server] Stacktrace:
[22.10 12:20:46] [Server] 	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.19.2-43.1.47.jar%2367!/:1.{}
[22.10 12:20:46] [Server] 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.8.jar%2354!/:?] {}
[22.10 12:20:46] [Server] 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.8.jar%2354!/:?] {}
[22.10 12:20:46] [Server] 	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar%2354!/:?] {}
[22.10 12:20:46] [Server] 	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.4.jar:?] {}
[22.10 12:20:46] [Server] 	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] {}
[22.10 12:20:46] [Server] 	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?] {}
[22.10 12:20:46] [Server] 	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] {}
[22.10 12:20:46] [Server] 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?] {}
[22.10 12:20:46] [Server] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
[22.10 12:20:46] [Server] 	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?] {re:mixin}
[22.10 12:20:46] [Server] 	at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?] {re:mixin}
[22.10 12:20:46] [Server] 	at java.lang.Class.privateGetPublicMethods(Class.java:3427) ~[?:?] {re:mixin}
[22.10 12:20:46] [Server] 	at java.lang.Class.privateGetPublicMethods(Class.java:3433) ~[?:?] {re:mixin}
[22.10 12:20:46] [Server] 	at java.lang.Class.getMethods(Class.java:2019) ~[?:?] {re:mixin}
[22.10 12:20:46] [Server] 	at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:83) ~[eventbus-6.0.3.jar%2351!/:?] {}
[22.10 12:20:46] [Server] 	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:126) ~[eventbus-6.0.3.jar%2351!/:?] {}
[22.10 12:20:46] [Server] 	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:61) ~[javafmllanguage-1.19.2-43.1.47.jar%23235!/:?] {}
[22.10 12:20:46] [Server] 	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:mixin}
[22.10 12:20:46] [Server] 	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:48) ~[javafmllanguage-1.19.2-43.1.47.jar%23235!/:?] {}
[22.10 12:20:46] [Server] 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:78) ~[javafmllanguage-1.19.2-43.1.47.jar%23235!/:?] {}
[22.10 12:20:46] [Server] 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.1.47.jar%23234!/:?] {}
[22.10 12:20:46] [Server] 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
[22.10 12:20:46] [Server] 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
[22.10 12:20:46] [Server] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
[22.10 12:20:46] [Server] 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
[22.10 12:20:46] [Server] 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
[22.10 12:20:46] [Server] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
[22.10 12:20:46] [Server] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
[22.10 12:20:46] [Server] -- System Details --
[22.10 12:20:46] [Server] Details:
[22.10 12:20:46] [Server] 	Minecraft Version1.19.2
[22.10 12:20:46] [Server] 	Minecraft Version ID1.19.2
[22.10 12:20:46] [Server] 	Operating SystemLinux (amd64) version 4.15.0-189-generic
[22.10 12:20:46] [Server] 	Java Version17.0.1, Oracle Corporation
[22.10 12:20:46] [Server] 	Java VM VersionJava HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
[22.10 12:20:46] [Server] 	Memory1367589392 bytes (1304 MiB) / 1761607680 bytes (1680 MiB) up to 12884901888 bytes (12288 MiB)
[22.10 12:20:46] [Server] 	CPUs32
[22.10 12:20:46] [Server] 	Processor VendorGenuineIntel
[22.10 12:20:46] [Server] 	Processor NameIntel(R) Xeon(R) CPU E5-2667 v4 @ 3.20GHz
[22.10 12:20:46] [Server] 	IdentifierIntel64 Family 6 Model 79 Stepping 1
[22.10 12:20:46] [Server] 	MicroarchitectureBroadwell (Server)
[22.10 12:20:46] [Server] 	Frequency (GHz)3.20
[22.10 12:20:46] [Server] 	Number of physical packages2
[22.10 12:20:46] [Server] 	Number of physical CPUs16
[22.10 12:20:46] [Server] 	Number of logical CPUs32
[22.10 12:20:46] [Server] 	Graphics card #name: ASPEED Graphics Family
[22.10 12:20:46] [Server] 	Graphics card #vendor: ASPEED Technology, Inc. (0x1a03)
[22.10 12:20:46] [Server] 	Graphics card #VRAM (MB): 0.00
[22.10 12:20:46] [Server] 	Graphics card #deviceId: 0x2000
[22.10 12:20:46] [Server] 	Graphics card #versionInfo: unknown
[22.10 12:20:46] [Server] 	Virtual memory max (MB)174694.83
[pastebin/gist/etc link here]

**Comment by MisterPeModder** [comment]
I'll fix this ASAP

**Comment by MisterPeModder** [comment]
Problem solved. The patch should be available for download in around 15 minutes.
