### ISSUE TITLE
Broken on 1.20.5

### ISSUE THREAD

**Issue by MFattakhov** [MisterPeModder/ShulkerBoxTooltip#151]
#### Issue Description:

Cannot start the game version 1.20.5 with current latest modpack version.

#### What happens:

Sometimes when I start the game it crashes, other times the game window doesn't appear.

#### Steps to reproduce:

1. install fabric 1.20.5
2. add shulkerboxtooltip as a mod
3. try to run the game
...

____
#### Affected Versions (Do *not* use "latest"):

- ShulkerBoxTooltip: 4.0.8
- Minecraft: 1.20.5
- Fabric Loader: 0.15.10
- Fabric API: 0.97.8

**Comment by ghost** [comment]
Can confirm on 1.20.6 fabric.

**Comment by sasch** [comment]
ShulkerBoxTooltip: 4.0.8
Minecraft: 1.20.6
Fabric Loader: 0.15.10
Fabric API: 0.97.8
Cloth Config API: 14.0.126

Does not work on my side! :-(

**Comment by LivelyBadGod** [comment]
Hey! Are there currently any updates on this issue?

**Comment by alovegit** [comment]
> Hey! Are there currently any updates on this issue?

He pushed changes the other day to make it work. I've been using the CI build until the official is released and haven't had any issues on 1.20.6.

**Comment by LivelyBadGod** [comment]
Thank you! I'll use that build then ^^

**Comment by jurohn** [comment]
> > Hey! Are there currently any updates on this issue?
> 
> He pushed changes the other day to make it work. I've been using the CI build until the official is released and haven't had any issues on 1.20.6.

```
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2024-05-15 00:31:10
Description: Bootstrap

java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2480 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at net.minecraft.class_2358.method_10199(class_2358.java:336)
	at net.minecraft.class_2966.method_12851(class_2966.java:53)
	at net.minecraft.client.main.Main.main(Main.java:170)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 10 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [shulkerboxtooltip-common.mixins.json:client.ShulkerBoxBlockMixin from mod shulkerboxtooltip] from phase [DEFAULT] in config [shulkerboxtooltip-common.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 13 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on onAppendTooltip could not find any targets matching 'Lnet/minecraft/class_2480;method_9568(Lnet/minecraft/class_1799;Lnet/minecraft/class_1922;Ljava/util/List;Lnet/minecraft/class_1836;)V' in net.minecraft.class_2480. Using refmap shulkerboxtooltip-common-common-refmap.json [PREINJECT Applicator Phase -> shulkerboxtooltip-common.mixins.json:client.ShulkerBoxBlockMixin from mod shulkerboxtooltip -> Prepare Injections ->  -> handler$dbo000$shulkerboxtooltip$onAppendTooltip(Lnet/minecraft/class_1799;Lnet/minecraft/class_1922;Ljava/util/List;Lnet/minecraft/class_1836;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:658)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:589)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308)
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:710)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1329)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 13 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at net.minecraft.class_2358.method_10199(class_2358.java:336)
	at net.minecraft.class_2966.method_12851(class_2966.java:53)


```

**Comment by sasch** [comment]
Since I can't create a CI build, I have to wait for the new version! :-(
Thanks for the update!

**Comment by alovegit** [comment]
> Since I can't create a CI build, I have to wait for the new version! :-( Thanks for the update!

You just download it from GitHub:  https://github.com/MisterPeModder/ShulkerBoxTooltip/actions/runs/9059071955/artifacts/1496175436

**Comment by venaminecraft** [comment]
Thanks for the update 🥳

**Comment by MisterPeModder** [comment]
Sorry for the long wait, I released the mod for 1.20.6
This version is still a work-in-progress though, networking support (ender chest previews) is disabled and support for Forge is removed (I will probably migrate to NeoForge due to a missing dependency).

**Comment by kiyoshi-shikuma** [comment]
Any chance of a 1.20.5 release as well? I've seen a couple other mods also skip to 1.20.6 and not release 1.20.5, is there a reason?

**Comment by alovegit** [comment]
> Any chance of a 1.20.5 release as well? I've seen a couple other mods also skip to 1.20.6 and not release 1.20.5, is there a reason?

1.20.6 came out a week or less after and was a tiny hotfix for 1.20.5.  So, there is no reason to use 1.20.5.
