### ISSUE TITLE
1.21 Quilt server not starting up with the mod present

### ISSUE THREAD

**Issue by manuelgrabowski** [MisterPeModder/ShulkerBoxTooltip#169]
#### What happens:

Just updated my server to 1.21, and unfortunately I can only get it to start up when removing this mod.

#### What you expected to happen:

Playing with this super essential mod :)

What's odd is that it works fine with the same versions on my client. The only mod that is server-side only is `servux-fabric-1.21.0-0.2.0.jar`, but the crash remains when I remove that one.

#### Steps to reproduce:

-

____
#### Affected Versions (Do *not* use "latest"):

- ShulkerBoxTooltip: shulkerboxtooltip-fabric-5.0.3+1.21
- Minecraft: 1.21
- Fabric Loader: Quilt 0.26.1-beta1
- Fabric API: quilted-fabric-api-11.0.0-alpha.2+0.100.4-1.21
- Other mods (if relevant):
  - AnvilNeverTooExpensive-fabric-1.21-1.2.jar
  - badpackets-fabric-0.8.1.jar
  - BowInfinityFix-1.21-fabric-3.1.0.jar
  - carpet-extra-1.21-1.4.147.jar
  - fabric-carpet-1.21-1.4.147+v240613.jar
  - head-name-fix-1.21-1.3.1.jar
  - improvedsigns-1.4.2.jar
  - lithium-fabric-mc1.21-0.12.7.jar
  - quilted-fabric-api-11.0.0-alpha.2+0.100.4-1.21.jar
  - servux-fabric-1.21.0-0.2.0.jar

#### Your most recent log file where the issue was present: 

```
[00:07:21] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/data/libraries/net/fabricmc/sponge-mixin/0.13.3+mixin.0.8.5/sponge-mixin-0.13.3+mixin.0.8.5.jar Service=Knot/Quilt Env=SERVER
[00:07:21] [main/INFO]: Compatibility level set to JAVA_17
[00:07:21] [main/INFO]: Compatibility level set to JAVA_21
[00:07:21] [main/INFO]: Loaded configuration file for Lithium: 138 options available, 0 override(s) found
[00:07:22] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[00:07:22] [main/WARN]: Configuration conflict: there is more than one oshi.properties file on the classpath: [quilt.zfs://minecraft-1.21.i0:0/oshi.properties, jar:file:/data/libraries/com/github/oshi/oshi-core/6.4.10/oshi-core-6.4.10.jar!/oshi.properties]
[00:07:22] [main/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath: [quilt.zfs://minecraft-1.21.i0:0/oshi.architecture.properties, jar:file:/data/libraries/com/github/oshi/oshi-core/6.4.10/oshi-core-6.4.10.jar!/oshi.architecture.properties]
[00:07:27] [main/INFO]: Improved Signs Initializing
[00:07:27] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'shulkerboxtooltip'!
        at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$2(EntrypointUtils.java:66) ~[quilt-loader-0.26.1-beta.1.jar:?]
        at org.quiltmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:34) ~[quilt-loader-0.26.1-beta.1.jar:?]
        at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:64) ~[quilt-loader-0.26.1-beta.1.jar:?]
        at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invokeContainer(EntrypointUtils.java:49) ~[quilt-loader-0.26.1-beta.1.jar:?]
        at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[quilt-loader-0.26.1-beta.1.jar:?]
        at org.quiltmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:65) ~[quilt-loader-0.26.1-beta.1.jar:?]
        at net.minecraft.server.Main.main(Main.java:111) [minecraft-1.21.i0:0/:?]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:557) [quilt-loader-0.26.1-beta.1.jar:?]
        at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84) [quilt-loader-0.26.1-beta.1.jar:?]
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:31) [quilt-loader-0.26.1-beta.1.jar:?]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at org.quiltmc.loader.impl.launch.server.QuiltServerLauncher.main(QuiltServerLauncher.java:66) [quilt-loader-0.26.1-beta.1.jar:?]
Caused by: java.lang.RuntimeException: Cannot load com.misterpemodder.shulkerboxtooltip.impl.config.Configuration$ColorsCategory because Mismatched @Envrionment
        at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:292) ~[quilt-loader-0.26.1-beta.1.jar:?]
        at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClassOnly(KnotClassDelegate.java:188) ~[quilt-loader-0.26.1-beta.1.jar:?]
        at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:174) ~[quilt-loader-0.26.1-beta.1.jar:?]
        at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:239) ~[quilt-loader-0.26.1-beta.1.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at java.base/java.lang.Class.getDeclaredFields0(Native Method) ~[?:?]
        at java.base/java.lang.Class.privateGetDeclaredFields(Unknown Source) ~[?:?]
        at java.base/java.lang.Class.getDeclaredFields(Unknown Source) ~[?:?]
        at com.misterpemodder.shulkerboxtooltip.impl.tree.RootConfigNode$Builder.build(RootConfigNode.java:149) ~[shulkerboxtooltip-5.0.31.21.i0:0/:?]
        at com.misterpemodder.shulkerboxtooltip.impl.tree.RootConfigNode.create(RootConfigNode.java:39) ~[shulkerboxtooltip-5.0.31.21.i0:0/:?]
        at com.misterpemodder.shulkerboxtooltip.ShulkerBoxTooltip.init(ShulkerBoxTooltip.java:45) ~[shulkerboxtooltip-5.0.31.21.i0:0/:?]
        at com.misterpemodder.shulkerboxtooltip.fabric.ShulkerBoxTooltipImpl.onInitialize(ShulkerBoxTooltipImpl.java:14) ~[shulkerboxtooltip-5.0.31.21.i0:0/:?]
        at org.quiltmc.loader.impl.game.minecraft.Hooks.lambda$startServer$2(Hooks.java:65) ~[quilt-loader-0.26.1-beta.1.jar:?]
        at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke$0(EntrypointUtils.java:36) ~[quilt-loader-0.26.1-beta.1.jar:?]
        at org.quiltmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:62) ~[quilt-loader-0.26.1-beta.1.jar:?]
        ... 12 more
```

**Comment by MisterPeModder** [comment]
Fixed! For some reason this crash does not occur on Fabric servers, so I didn't encounter it while testing.
