### ISSUE TITLE
The game crashed whilst initializing game

### ISSUE THREAD

**Issue by mrdgo** [MisterPeModder/ShulkerBoxTooltip#172]
#### Issue Description:

When starting the game, I get:
```
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'shulkerboxtooltip'!
```
With exit code 255

#### What happens:

The game crashes when I try to load this mod on start.

#### What you expected to happen:

No crash.

#### Steps to reproduce:

What I tried so far:

1. put the mod in my mods/ folder with other mods -> crash
2. put only this mod in my mods/ folder -> crash with different error message
3. post here

____
#### Affected Versions (Do *not* use "latest"):

- ShulkerBoxTooltip: 5.0.4
- Minecraft: 1.21
- Fabric Loader: 0.15.11-1.21
- Fabric API: if needed, how do I obtain?
- Other mods (if relevant): minihud-fabric-1.21-0.31.999-sakura.12.jar, modmenu-11.0.1.jar, litematica-fabric-1.21-0.19.2.jar, shulkerplus-mc1.21-v1.3.3-fabric.jar, itemscroller-fabric-1.21-0.23.999-sakura.8.jar, malilib-fabric-1.21.0-0.20.2.jar               

#### Your most recent log file where the issue was present: 

Crash-report with the other mods present:
```
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 2024-08-19 12:34:36
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'shulkerboxtooltip'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:477)
	at net.minecraft.client.main.Main.main(Main.java:239)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/client/rendering/v1/TooltipComponentCallback
	at com.misterpemodder.shulkerboxtooltip.fabric.ShulkerBoxTooltipClientImpl.onInitializeClient(ShulkerBoxTooltipClientImpl.java:18)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.client.rendering.v1.TooltipComponentCallback
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 8 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:477)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:239)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Linux (amd64) version 6.10.5-arch1-1
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 417651216 bytes (398 MiB) / 671088640 bytes (640 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i7-1260P
	Identifier: Intel64 Family 6 Model 154 Stepping 3
	Microarchitecture: Alder Lake
	Frequency (GHz): 4.70
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 16
	Graphics card #0 name: Alder Lake-P GT2 [Iris Xe Graphics]
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MiB): 256.00
	Graphics card #0 deviceId: 0x46a6
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MiB): 48666.00
	Virtual memory used (MiB): 15191.03
	Swap memory total (MiB): 32768.00
	Swap memory used (MiB): 2.00
	Space in storage for jna.tmpdir (MiB): available: 1396831.25, total: 1812310.75
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 1396831.25, total: 1812310.75
	Space in storage for io.netty.native.workdir (MiB): available: 1396831.25, total: 1812310.75
	Space in storage for java.io.tmpdir (MiB): available: 15890.16, total: 15898.00
	Space in storage for workdir (MiB): available: 1396831.25, total: 1812310.75
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: fabric-loader-0.15.11-1.21
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: Unknown
	Window size: <not initialized>
	GFLW Platform: <error>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 404
	Type: Client (map_client.txt)
	Locale: en_US
	System encoding: UTF-8
	File encoding: UTF-8
	CPU: <unknown>
```

Message when only ShulkerBoxTooltip is in my mods folder:
```
Mod 'Shulker Box Tooltip' (shulkerboxtooltip) 5.0.4+1.21 requires any version of fabric-resource-loader-v0, which is missing!
```
I can't find the dependency in question.
No crash-report is produced but a logfile is written:
```
[15:45:28] [main/INFO]: Loading Minecraft 1.21 with Fabric Loader 0.15.11
[15:45:28] [main/WARN]: Mod resolution failed
[15:45:28] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE shulkerboxtooltip 5.0.4+1.21 {depends fabric-resource-loader-v0 @ [*]}, ROOT_FORCELOAD_SINGLE shulkerboxtooltip 5.0.4+1.21]
[15:45:28] [main/INFO]: Reason: [HARD_DEP shulkerboxtooltip 5.0.4+1.21 {depends fabric-resource-loader-v0 @ [*]}]
[15:45:28] [main/INFO]: Fix: add [add:fabric-resource-loader-v0 1 ([(-∞,∞)])], remove [], replace []
[15:45:28] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	- Install fabric-resource-loader-v0, any version.
More details:
	- Mod 'Shulker Box Tooltip' (shulkerboxtooltip) 5.0.4+1.21 requires any version of fabric-resource-loader-v0, which is missing!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.11.jar:?]
```

**Comment by MisterPeModder** [comment]
Fabric API is the primary dependency of most Fabric mods, the fact that only ShulkerBoxTooltip requires it in your mod pack is pretty (un)lucky.
Anyways, you may download it from [Modrinth](https://modrinth.com/mod/fabric-api) or [Curseforge](https://www.curseforge.com/minecraft/mc-mods/fabric-api).
Let me know if that works for you.

**Comment by mrdgo** [comment]
TY, that was it :)
