### ISSUE TITLE
Can't connect to Hypixel with Server Integration enabled

### ISSUE THREAD

**Issue by Luracasmus** [MisterPeModder/ShulkerBoxTooltip#43]
#### Issue Description:
When ShulkerBoxTooltip is installed and Server Integration is enabled, you can't connect to Hypixel.

#### What happens:
This error appears in chat and you're sent to a limbo server.

![image](https://user-images.githubusercontent.com/77991691/108036522-9da13780-7038-11eb-80d0-42067c5f4ef4.png)

#### What you expected to happen:
You get sent to a lobby server and can play.

#### Steps to reproduce:
1. Install ShulkerBoxTooltip
2. Enable Server Integration
3. Join `mc.hypixel.net`

#### Affected Versions (Do *not* use "latest"):
- ShulkerBoxTooltip: 2.3.5+1.16.5
- Minecraft: 1.16.5
- Fabric Loader: 0.11.1-1.16.5
- Fabric API: 0.30.3+1.16

#### Your most recent log file where the issue was present:
[latest.log](https://github.com/MisterPeModder/ShulkerBoxTooltip/files/5987087/latest.log)

**Comment by ErikS270102** [comment]
Same Problem here, I believe this is the Error Log:

```
[18:29:03] [main/FATAL]: Error executing task on Client
java.lang.NullPointerException: null
	at Not Enough Crashes deobfuscated stack trace.(1.16.4+build.9) ~[?:?]
	at net.minecraft.scoreboard.Scoreboard.removeTeam(Scoreboard:199) ~[?:?]
	at net.minecraft.client.network.ClientPlayNetworkHandler.onTeam(ClientPlayNetworkHandler:2156) ~[?:?]
	at net.minecraft.network.packet.s2c.play.TeamS2CPacket.apply(TeamS2CPacket:122) ~[?:?]
	at net.minecraft.network.packet.s2c.play.TeamS2CPacket.apply(TeamS2CPacket:16) ~[?:?]
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:21) ~[?:?]
	at net.minecraft.class_2600$$Lambda$4565/428252991.run(Unknown Source) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:144) ~[?:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:118) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:103) ~[?:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1015) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:681) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:215) [intermediary-fabric-loader-0.11.1-1.16.4.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139) [fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.11.1.jar:?]
```

**Comment by blueforce-aero** [comment]
even happens to me with server integration disabled

**Comment by MisterPeModder** [comment]
I can reproduce the issue on my machine, however, it seems this is a problem on their end.
To connect to the server, just turn off server integration in the config (I tested it, it works), or remove/disable the mod since Hypixel  is stuck on 1.8, there won't be any shulker boxes
