### ISSUE TITLE
Client load crash on 1.17 Fabric.

### ISSUE THREAD

**Issue by ToasterBorst** [MisterPeModder/ShulkerBoxTooltip#52]
Found what I believe is the relevant error in launcher_log.txt, apologies if this isn't what you're looking for.

```
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:228)

	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)

	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

Caused by: java.lang.reflect.InvocationTargetException

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)

	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.base/java.lang.reflect.Method.invoke(Method.java:567)

	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)

	... 2 more

Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered

	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)

	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)

	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)

	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)

	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)

	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)

	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)

	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:185)

	at net.minecraft.class_128.<init>(class_128.java:44)

	at net.minecraft.class_128.method_24305(class_128.java:349)

	at net.minecraft.client.main.Main.main(Main.java:137)

	... 7 more

Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Argument modifier method updateTooltipLeftAndBottomPos(Lnet/minecraft/class_1159;Lnet/minecraft/class_287;IIIIIII)I in shulkerboxtooltip.client.json:ScreenMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap com.misterpemodder.shulkerboxtooltip

	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)

	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)

	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)

	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)

	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)

	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)

	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)

	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)

	... 17 more
```

**Comment by MisterPeModder** [comment]
You are using a version of the mod designed for Minecraft 1.16 on 1.17. Don't thrust the 'Download' button of Curseforge, prefer downloading the specific version instead.

**Comment by ToasterBorst** [comment]
I see, alpha releases are hidden by default under files on CurseForge. My bad bro.
