### ISSUE TITLE
Crashing randomly when mousing over shulker box

### ISSUE THREAD

**Issue by purejosh** [MisterPeModder/ShulkerBoxTooltip#73]
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 1/24/22, 10:25 PM
Description: Rendering screen

java.lang.ArrayIndexOutOfBoundsException: Index -128 out of bounds for length 27
	at java.base/java.util.Arrays$ArrayList.set(Arrays.java:4170)
	at net.minecraft.class_2371.set(class_2371.java:54)
	at com.misterpemodder.shulkerboxtooltip.api.provider.BlockEntityPreviewProvider.getInventory(BlockEntityPreviewProvider.java:107)
	at com.misterpemodder.shulkerboxtooltip.api.provider.BlockEntityPreviewProvider.addTooltip(BlockEntityPreviewProvider.java:142)
	at com.misterpemodder.shulkerboxtooltip.impl.provider.ShulkerBoxPreviewProvider.addTooltip(ShulkerBoxPreviewProvider.java:60)
	at com.misterpemodder.shulkerboxtooltip.impl.ShulkerBoxTooltipClient.modifyStackTooltip(ShulkerBoxTooltipClient.java:111)
	at net.minecraft.class_1799.handler$zni000$onGetTooltip(class_1799.java:3160)
	at net.minecraft.class_1799.method_7950(class_1799.java:811)
	at net.minecraft.class_437.method_25408(class_437.java:182)
	at net.minecraft.class_437.method_25409(class_437.java:169)
	at net.minecraft.class_465.method_2380(class_465.java:190)
	at net.minecraft.class_495.method_25394(class_495.java:24)
	at net.minecraft.class_757.method_3192(class_757.java:1279)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.Arrays$ArrayList.set(Arrays.java:4170)
	at net.minecraft.class_2371.set(class_2371.java:54)
	at com.misterpemodder.shulkerboxtooltip.api.provider.BlockEntityPreviewProvider.getInventory(BlockEntityPreviewProvider.java:107)
	at com.misterpemodder.shulkerboxtooltip.api.provider.BlockEntityPreviewProvider.addTooltip(BlockEntityPreviewProvider.java:142)
	at com.misterpemodder.shulkerboxtooltip.impl.provider.ShulkerBoxPreviewProvider.addTooltip(ShulkerBoxPreviewProvider.java:60)
	at com.misterpemodder.shulkerboxtooltip.impl.ShulkerBoxTooltipClient.modifyStackTooltip(ShulkerBoxTooltipClient.java:111)
	at net.minecraft.class_1799.handler$zni000$onGetTooltip(class_1799.java:3160)
	at net.minecraft.class_1799.method_7950(class_1799.java:811)
	at net.minecraft.class_437.method_25408(class_437.java:182)
	at net.minecraft.class_437.method_25409(class_437.java:169)
	at net.minecraft.class_465.method_2380(class_465.java:190)
	at net.minecraft.class_495.method_25394(class_495.java:24)

-- Screen render details --
Details:
	Screen name: net.minecraft.class_495
	Mouse location: Scaled: (343, 285). Absolute: (1716.000000, 1425.000000)
	Screen size: Scaled: (768, 432). Absolute: (3840, 2160). Scale factor of 5.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:1279)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['purejosh'/354407, l='ClientLevel', x=124.74, y=152.00, z=-787.85]]
	Chunk stats: 3025, 2415
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,71,0), Section: (at 0,7,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 162239 game time, 34702907 day time
	Server brand: Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:517)
	at net.minecraft.class_310.method_1587(class_310.java:2402)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 2
	Reload reason: manual
	Finished: Yes
	Packs: Default, Fabric Mods, Bare+Bones+1.16.zip, VanillaTweaks_r662487.zip, 53a6111d3fadba045f98a338ec5ac88a37c068a9

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 435915248 bytes (415 MiB) / 2315255808 bytes (2208 MiB) up to 17179869184 bytes (16384 MiB)
	CPUs: 32
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 9 5950X 16-Core Processor            
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.39
	Number of physical packages: 1
	Number of physical CPUs: 16
	Number of logical CPUs: 32
	Graphics card #0 name: NVIDIA GeForce RTX 3090
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2204
	Graphics card #0 versionInfo: DriverVersion=30.0.14.9709
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 50105.04
	Virtual memory used (MB): 25834.16
	Swap memory total (MB): 17408.00
	Swap memory used (MB): 103.35
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx16G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.4.3
		architectury: Architectury 3.4.9
		chunky: Chunky 1.2.164
		cloth-api: Cloth API 3.0.55
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-client-events-v0: Cloth Client Events v0 3.0.55
		cloth-common-events-v1: Cloth Common Events v1 3.0.55
		cloth-config: Cloth Config v6 6.1.48
		cloth-datagen-api-v1: Cloth Datagen v1 3.0.55
		cloth-scissors-api-v1: Cloth Scissors API v1 3.0.55
		cloth-utils-v1: Cloth Utils v1 3.0.55
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		crowdin-translate: CrowdinTranslate 1.4+1.18
		durabilityviewer: Giselbaers Durability Viewer 1.18-fabric0.43.1-1.10.2
		dynamicfps: Dynamic FPS 2.0.6
		entityculling: EntityCulling-Fabric 1.3.3
		fabric: Fabric API 0.45.2+1.18
		fabric-api-base: Fabric API Base 0.4.1+b4f4f6cd65
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.0+17be577f65
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+ded849a965
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.9+3ac43d9565
		fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d9565
		fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c665
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73d65
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d9565
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.9+a1d9bbf565
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378a65
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.16+bfa23f1765
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.6+b4f4f6cd65
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d9565
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d9565
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.8+c8aba2f365
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.6+b4f4f6cd65
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca33565
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d9565
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d9565
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.8+b4f4f6cd65
		fabric-models-v0: Fabric Models (v0) 0.3.3+3ac43d9565
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d9565
		fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.1+3b82842e65
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.9+3ac43d9565
		fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1ac65
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.0+befed49e65
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.9+3ac43d9565
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.12+3ac43d9565
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.7+b4f4f6cd65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.4+7242e9d765
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d9565
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.9+b4f4f6cd65
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.3+6b21378a65
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d9565
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.7+3ac43d9565
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d9565
		fabric-structure-api-v1: Fabric Structure API (v1) 2.0.8+295197a765
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d9565
		fabric-textures-v0: Fabric Textures (v0) 1.0.9+3ac43d9565
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.5+fb3b57b465
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.6+b4f4f6cd65
		fabricloader: Fabric Loader 0.12.12
		gbfabrictools: GBfabrictools 1.3.4+1.18
		itemmodelfix: Item Model Fix 1.0.3+1.18
		java: OpenJDK 64-Bit Server VM 17
		lazydfu: LazyDFU 0.1.2
		minecraft: Minecraft 1.18.1
		mm: Manningham Mills 2.3
		modmenu: Mod Menu 3.0.1
		nofade: No Fade 1.18-2.0.1
		optifabric: OptiFabric 1.12.10
		org_codehaus_groovy_groovy: groovy 3.0.8
		org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.8
		quickcraft: Quickcraft 1.2.5
		shulkerboxtooltip: Shulker Box Tooltip 3.0.5+1.18
		slight-gui-modifications: 'Slight' GUI Modifications 2.0.2
		smoothboot: Smooth Boot 1.18-1.7.0
		worldedit: WorldEdit 7.2.8+6008-1246d61
		xaerominimap: Xaero's Minimap 21.23.0
		xaeroworldmap: Xaero's World Map 1.19.0
	Launched Version: fabric-loader-0.12.12-1.18.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 3090/PCIe/SSE2 GL version 3.2.0 NVIDIA 497.09, NVIDIA Corporation
	Window size: 3840x2160
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, file/Bare+Bones+1.16.zip (incompatible), file/VanillaTweaks_r662487.zip (incompatible)
	Current Language: English (US)
	CPU: 32x AMD Ryzen 9 5950X 16-Core Processor 
	OptiFine Version: OptiFine_1.18.1_HD_U_H4
	OptiFine Build: 20211212-175054
	Render Distance Chunks: 22
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: ComplementaryShaders_v4.3.3.zip
	OpenGlVersion: 3.2.0 NVIDIA 497.09
	OpenGlRenderer: NVIDIA GeForce RTX 3090/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 32

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.18.1
	OptiFine jar version: OptiFine_1.18.1_HD_U_H4
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: C:/Users/purejosh/AppData/Roaming/.minecraft/.optifine/OptiFine_1.18.1_HD_U_H4/Optifine-mapped.jar
	OptiFabric error: <None>

**Comment by MisterPeModder** [comment]
Fixed. It will be up in the next release for mc 1.17 & 1.18

**Comment by purejosh** [comment]
Thank you very much.
