### ISSUE TITLE
No config button in Mod menu

### ISSUE THREAD

**Issue by Nuaja** [MisterPeModder/ShulkerBoxTooltip#94]
#### Issue Description:

The button to access the config isn't there.

____
#### Affected Versions (Do *not* use "latest"):

- ShulkerBoxTooltip: 3.1.2
- Minecraft: 1.19.2
- Fabric Loader: 0.14.9
- Fabric API: 0.60.0
- Other mods (if relevant):

**Comment by MisterPeModder** [comment]
What do you mean by the config button?
Is the mod present in mod menu? If yes, you might have installed the forge version of the mod.
If that is not the case, can you post the list of mods you are using?

**Comment by Nuaja** [comment]
By the config button I mean this one: 
![unknown](https://user-images.githubusercontent.com/108593381/189643390-42523d5c-ab65-4512-8d96-454c7bfdf3b0.jpg)
I do have the right version of the mod (fabric).
I tested to see which mod might cause this, and turns out it's Cloth Config. Here's what it looks like when I add cloth config and no other mod (exept fabric api and mod menu):
![unknown](https://user-images.githubusercontent.com/108593381/189643971-82969f07-a1aa-4fea-a187-1d8fe82aee18.png)
As you can see I can't access the config menu. But I can when I remove Cloth Config.

**Comment by TechPro424** [comment]
Same issue here

**Comment by xKillswitch0** [comment]
I can't even get it to show up in Modmenu. I have the same setup as the OP.

**Comment by xVANKO** [comment]
Error log from PolyMC

```
[12:49:19] [Render thread/ERROR]: Error from mod 'shulkerboxtooltip'
java.lang.NoSuchMethodError: 'me.shedaniel.clothconfig2.impl.builders.KeyCodeBuilder me.shedaniel.clothconfig2.impl.builders.KeyCodeBuilder.setSaveConsumer(java.util.function.Consumer)'
	at com.misterpemodder.shulkerboxtooltip.impl.config.ConfigurationHandler.lambda$registerGui$9(ConfigurationHandler.java:91) ~[shulkerboxtooltip-fabric-3.1.2+1.19.2.jar:?]
	at me.shedaniel.autoconfig.gui.registry.GuiRegistry.lambda$get$3(GuiRegistry.java:74) ~[cloth-config-8.2.88-fabric.jar:?]
	at java.util.Optional.map(Unknown Source) ~[?:?]
	at me.shedaniel.autoconfig.gui.registry.GuiRegistry.get(GuiRegistry.java:74) ~[cloth-config-8.2.88-fabric.jar:?]
	at me.shedaniel.autoconfig.gui.registry.ComposedGuiRegistryAccess.lambda$get$0(ComposedGuiRegistryAccess.java:49) ~[cloth-config-8.2.88-fabric.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source) ~[?:?]
	at me.shedaniel.autoconfig.gui.registry.ComposedGuiRegistryAccess.get(ComposedGuiRegistryAccess.java:51) ~[cloth-config-8.2.88-fabric.jar:?]
	at me.shedaniel.autoconfig.gui.registry.api.GuiRegistryAccess.getAndTransform(GuiRegistryAccess.java:38) ~[cloth-config-8.2.88-fabric.jar:?]
	at me.shedaniel.autoconfig.gui.DefaultGuiProviders.lambda$getChildren$96(DefaultGuiProviders.java:538) ~[cloth-config-8.2.88-fabric.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
	at me.shedaniel.autoconfig.gui.DefaultGuiProviders.getChildren(DefaultGuiProviders.java:543) ~[cloth-config-8.2.88-fabric.jar:?]
	at me.shedaniel.autoconfig.gui.DefaultGuiProviders.getChildren(DefaultGuiProviders.java:530) ~[cloth-config-8.2.88-fabric.jar:?]
	at me.shedaniel.autoconfig.gui.registry.GuiRegistry.lambda$get$3(GuiRegistry.java:74) ~[cloth-config-8.2.88-fabric.jar:?]
	at java.util.Optional.map(Unknown Source) ~[?:?]
	at me.shedaniel.autoconfig.gui.registry.GuiRegistry.get(GuiRegistry.java:74) ~[cloth-config-8.2.88-fabric.jar:?]
	at me.shedaniel.autoconfig.gui.registry.ComposedGuiRegistryAccess.lambda$get$0(ComposedGuiRegistryAccess.java:49) ~[cloth-config-8.2.88-fabric.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source) ~[?:?]
	at me.shedaniel.autoconfig.gui.registry.ComposedGuiRegistryAccess.get(ComposedGuiRegistryAccess.java:51) ~[cloth-config-8.2.88-fabric.jar:?]
	at me.shedaniel.autoconfig.gui.registry.api.GuiRegistryAccess.getAndTransform(GuiRegistryAccess.java:38) ~[cloth-config-8.2.88-fabric.jar:?]
	at me.shedaniel.autoconfig.gui.ConfigScreenProvider.lambda$get$5(ConfigScreenProvider.java:129) ~[cloth-config-8.2.88-fabric.jar:?]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:?]
	at me.shedaniel.autoconfig.gui.ConfigScreenProvider.lambda$get$6(ConfigScreenProvider.java:126) ~[cloth-config-8.2.88-fabric.jar:?]
	at java.util.LinkedHashMap.forEach(Unknown Source) ~[?:?]
	at me.shedaniel.autoconfig.gui.ConfigScreenProvider.get(ConfigScreenProvider.java:125) ~[cloth-config-8.2.88-fabric.jar:?]
	at com.misterpemodder.shulkerboxtooltip.impl.ModMenuCompat.lambda$getModConfigScreenFactory$0(ModMenuCompat.java:24) ~[shulkerboxtooltip-fabric-3.1.2+1.19.2.jar:?]
	at com.terraformersmc.modmenu.ModMenu.getConfigScreen(ModMenu.java:52) ~[modmenu-4.0.6.jar:?]
	at com.terraformersmc.modmenu.gui.ModsScreen.method_25426(ModsScreen.java:117) ~[modmenu-4.0.6.jar:?]
	at net.minecraft.class_437.method_41843(class_437.java:389) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25423(class_437.java:380) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1507(class_310.java:1035) ~[client-intermediary.jar:?]
	at com.terraformersmc.modmenu.gui.widget.ModMenuButtonWidget.lambda$new$0(ModMenuButtonWidget.java:11) ~[modmenu-4.0.6.jar:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:43) ~[client-intermediary.jar:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:16) ~[client-intermediary.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:120) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:27) ~[client-intermediary.jar:?]
	at net.minecraft.class_442.method_25402(class_442.java:343) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:489) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:165) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:103) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:165) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) [lwjgl-glfw-3.3.1.jar:build 7]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:build 7]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474) [lwjgl-glfw-3.3.1.jar:build 7]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:222) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1208) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:768) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423) [quilt-loader-0.17.4.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76) [quilt-loader-0.17.4.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24) [quilt-loader-0.17.4.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175) [NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185) [NewLaunch.jar:?]
	at org.polymc.EntryPoint.listen(EntryPoint.java:144) [NewLaunch.jar:?]
	at org.polymc.EntryPoint.main(EntryPoint.java:74) [NewLaunch.jar:?]
```

**Comment by Sprial404** [comment]
There was a change in [Cloth Config API commit](https://github.com/shedaniel/cloth-config/commit/06514ac938be6f6d165e07e5e4ac3ebc22432625#diff-7fbf37c94357ffd1747792d68754f7288e6267a12699b16d3c4e2937a6e19212L85-R87)

**Comment by MisterPeModder** [comment]
The bundled version of cloth has been updated to v8. A new patch will be released shortly.
Thanks for reporting the issue!
