### ISSUE TITLE
Config button missing in 1.18.2

### ISSUE THREAD

**Issue by ninlego** [MisterPeModder/ShulkerBoxTooltip#95]
#### Issue Description:

Config button is also missing in 1.18.2 and possibly other versions as well

#### What happens:
Config button is missing in modmenu

#### What you expected to happen:
The button should be there

**Comment by Disguys** [comment]
These errors appear when you enter the Mod Menu on Fabric 1.18.2 with latest version of SBT
I think this will help the developer fix the problem.
```
[15:35:53] [Render thread/ERROR]: Error from mod 'shulkerboxtooltip'
java.lang.NoSuchMethodError: 'me.shedaniel.clothconfig2.impl.builders.KeyCodeBuilder me.shedaniel.clothconfig2.impl.builders.KeyCodeBuilder.setSaveConsumer(java.util.function.Consumer)'
	at com.misterpemodder.shulkerboxtooltip.impl.config.ConfigurationHandler.lambda$registerGui$9(ConfigurationHandler.java:94) ~[shulkerboxtooltip-3.1.1+1.18.2.jar:?]
	at me.shedaniel.autoconfig.gui.registry.GuiRegistry.lambda$get$3(GuiRegistry.java:74) ~[cloth-config-6.4.90-fabric.jar:?]
	at java.util.Optional.map(Unknown Source) ~[?:?]
	at me.shedaniel.autoconfig.gui.registry.GuiRegistry.get(GuiRegistry.java:74) ~[cloth-config-6.4.90-fabric.jar:?]
	at me.shedaniel.autoconfig.gui.registry.ComposedGuiRegistryAccess.lambda$get$0(ComposedGuiRegistryAccess.java:49) ~[cloth-config-6.4.90-fabric.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source) ~[?:?]
	at me.shedaniel.autoconfig.gui.registry.ComposedGuiRegistryAccess.get(ComposedGuiRegistryAccess.java:51) ~[cloth-config-6.4.90-fabric.jar:?]
	at me.shedaniel.autoconfig.gui.registry.api.GuiRegistryAccess.getAndTransform(GuiRegistryAccess.java:38) ~[cloth-config-6.4.90-fabric.jar:?]
	at me.shedaniel.autoconfig.gui.DefaultGuiProviders.lambda$getChildren$96(DefaultGuiProviders.java:540) ~[cloth-config-6.4.90-fabric.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
	at me.shedaniel.autoconfig.gui.DefaultGuiProviders.getChildren(DefaultGuiProviders.java:545) ~[cloth-config-6.4.90-fabric.jar:?]
	at me.shedaniel.autoconfig.gui.DefaultGuiProviders.getChildren(DefaultGuiProviders.java:532) ~[cloth-config-6.4.90-fabric.jar:?]
	at me.shedaniel.autoconfig.gui.registry.GuiRegistry.lambda$get$3(GuiRegistry.java:74) ~[cloth-config-6.4.90-fabric.jar:?]
	at java.util.Optional.map(Unknown Source) ~[?:?]
	at me.shedaniel.autoconfig.gui.registry.GuiRegistry.get(GuiRegistry.java:74) ~[cloth-config-6.4.90-fabric.jar:?]
	at me.shedaniel.autoconfig.gui.registry.ComposedGuiRegistryAccess.lambda$get$0(ComposedGuiRegistryAccess.java:49) ~[cloth-config-6.4.90-fabric.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source) ~[?:?]
	at me.shedaniel.autoconfig.gui.registry.ComposedGuiRegistryAccess.get(ComposedGuiRegistryAccess.java:51) ~[cloth-config-6.4.90-fabric.jar:?]
	at me.shedaniel.autoconfig.gui.registry.api.GuiRegistryAccess.getAndTransform(GuiRegistryAccess.java:38) ~[cloth-config-6.4.90-fabric.jar:?]
	at me.shedaniel.autoconfig.gui.ConfigScreenProvider.lambda$get$5(ConfigScreenProvider.java:130) ~[cloth-config-6.4.90-fabric.jar:?]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:?]
	at me.shedaniel.autoconfig.gui.ConfigScreenProvider.lambda$get$6(ConfigScreenProvider.java:127) ~[cloth-config-6.4.90-fabric.jar:?]
	at java.util.LinkedHashMap.forEach(Unknown Source) ~[?:?]
	at me.shedaniel.autoconfig.gui.ConfigScreenProvider.get(ConfigScreenProvider.java:126) ~[cloth-config-6.4.90-fabric.jar:?]
	at com.misterpemodder.shulkerboxtooltip.impl.ModMenuCompat.lambda$getModConfigScreenFactory$0(ModMenuCompat.java:24) ~[shulkerboxtooltip-3.1.1+1.18.2.jar:?]
	at com.terraformersmc.modmenu.ModMenu.getConfigScreen(ModMenu.java:53) ~[modmenu-3.2.3.jar:?]
	at com.terraformersmc.modmenu.gui.ModsScreen.method_25426(ModsScreen.java:120) ~[modmenu-3.2.3.jar:?]
	at net.minecraft.class_437.redirect$cib000$onInit(class_437.java:5278) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25423(class_437.java:389) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1507(class_310.java:993) ~[client-intermediary.jar:?]
	at com.terraformersmc.modmenu.gui.widget.ModMenuButtonWidget.lambda$new$0(ModMenuButtonWidget.java:11) ~[modmenu-3.2.3.jar:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:40) ~[client-intermediary.jar:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:16) ~[client-intermediary.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:121) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:27) ~[client-intermediary.jar:?]
	at net.minecraft.class_442.method_25402(class_442.java:354) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:492) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:165) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:103) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:165) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) [lwjgl-glfw-3.2.2.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:?]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) [lwjgl-glfw-3.2.2.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:222) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1150) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:737) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.9.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175) [NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185) [NewLaunch.jar:?]
	at org.polymc.EntryPoint.listen(EntryPoint.java:144) [NewLaunch.jar:?]
	at org.polymc.EntryPoint.main(EntryPoint.java:74) [NewLaunch.jar:?]```

**Comment by MisterPeModder** [comment]
The bug is occuring in the 1.17 branch too, I'll fix that one next.
