### ISSUE TITLE
Client error in the log

### ISSUE THREAD

**Issue by ghost** [MisterPeModder/ShulkerBoxTooltip#99]
Hello, everything works fine but I saw this bug in the log.
Any clue?

Error from mod 'shulkerboxtooltip'
java.lang.NoSuchMethodError: 'me.shedaniel.clothconfig2.impl.builders.KeyCodeBuilder me.shedaniel.clothconfig2.impl.builders.KeyCodeBuilder.setKeySaveConsumer(java.util.function.Consumer)'
	at Not Enough Crashes deobfuscated stack trace.(1.19.2+build.18)
	at com.misterpemodder.shulkerboxtooltip.impl.config.ConfigurationHandler.lambda$registerGui$9(ConfigurationHandler.java:91)
	at me.shedaniel.autoconfig.gui.registry.GuiRegistry.lambda$get$3(GuiRegistry.java:74)
	at java.util.Optional.map(Optional.java:260)
	at me.shedaniel.autoconfig.gui.registry.GuiRegistry.get(GuiRegistry.java:74)
	at me.shedaniel.autoconfig.gui.registry.ComposedGuiRegistryAccess.lambda$get$0(ComposedGuiRegistryAccess.java:49)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at me.shedaniel.autoconfig.gui.registry.ComposedGuiRegistryAccess.get(ComposedGuiRegistryAccess.java:51)
	at me.shedaniel.autoconfig.gui.registry.api.GuiRegistryAccess.getAndTransform(GuiRegistryAccess.java:38)
	at me.shedaniel.autoconfig.gui.DefaultGuiProviders.lambda$getChildren$67(DefaultGuiProviders.java:375)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at me.shedaniel.autoconfig.gui.DefaultGuiProviders.getChildren(DefaultGuiProviders.java:380)
	at me.shedaniel.autoconfig.gui.DefaultGuiProviders.getChildren(DefaultGuiProviders.java:367)
	at me.shedaniel.autoconfig.gui.registry.GuiRegistry.lambda$get$3(GuiRegistry.java:74)
	at java.util.Optional.map(Optional.java:260)
	at me.shedaniel.autoconfig.gui.registry.GuiRegistry.get(GuiRegistry.java:74)
	at me.shedaniel.autoconfig.gui.registry.ComposedGuiRegistryAccess.lambda$get$0(ComposedGuiRegistryAccess.java:49)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at me.shedaniel.autoconfig.gui.registry.ComposedGuiRegistryAccess.get(ComposedGuiRegistryAccess.java:51)
	at me.shedaniel.autoconfig.gui.registry.api.GuiRegistryAccess.getAndTransform(GuiRegistryAccess.java:38)
	at me.shedaniel.autoconfig.gui.ConfigScreenProvider.lambda$get$5(ConfigScreenProvider.java:129)
	at java.util.ArrayList.forEach(ArrayList.java:1511)
	at me.shedaniel.autoconfig.gui.ConfigScreenProvider.lambda$get$6(ConfigScreenProvider.java:126)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at me.shedaniel.autoconfig.gui.ConfigScreenProvider.get(ConfigScreenProvider.java:125)
	at com.misterpemodder.shulkerboxtooltip.impl.ModMenuCompat.lambda$getModConfigScreenFactory$0(ModMenuCompat.java:24)
	at com.terraformersmc.modmenu.ModMenu.getConfigScreen(ModMenu.java:52)
	at com.terraformersmc.modmenu.gui.ModsScreen.init(ModsScreen.java:117)
	at net.minecraft.client.gui.screen.Screen.clearAndInit(Screen:389)
	at net.minecraft.client.gui.screen.Screen.init(Screen:380)
	at net.minecraft.client.MinecraftClient.setScreen(MinecraftClient:1035)
	at com.terraformersmc.modmenu.gui.widget.ModMenuButtonWidget.lambda$new$0(ModMenuButtonWidget.java:11)
	at net.minecraft.client.gui.widget.ButtonWidget.onPress(ButtonWidget:43)
	at net.minecraft.client.gui.widget.PressableWidget.onClick(PressableWidget:16)
	at net.minecraft.client.gui.widget.ClickableWidget.mouseClicked(ClickableWidget:120)
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement:537)
	at net.minecraft.client.Mouse.method_1611(Mouse:94)
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:489)
	at net.minecraft.client.Mouse.onMouseButton(Mouse:94)
	at net.minecraft.client.Mouse.method_22686(Mouse:165)
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:103)
	at net.minecraft.client.Mouse.method_22684(Mouse:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem:197)
	at net.minecraft.client.util.Window.swapBuffers(Window:315)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1205)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:768)
	at net.minecraft.client.main.Main.main(Main:244)
	at net.minecraft.client.main.Main.main(Main:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by MisterPeModder** [comment]
Hi, what version of cloth-config are you running?
You can see it by clicking the 'Show Libraries' button in mod menu.

**Comment by ghost** [comment]
The newest, the mod name says v8.0.75.

![image](https://user-images.githubusercontent.com/75373609/196153132-08616378-dd8b-4d67-8544-4c0da4bc63b0.png)

**Comment by MisterPeModder** [comment]
I was asking for the version that gets loaded in-game, but version 8.0.75 is not the latest version of cloth config, the version is 8.2.88.

The fix I made for the button disappearing only version from this version onward for now, I fix address this compatibility problem in a patch shortly.

**Comment by ghost** [comment]
I was a bit in rush and thought it does the same.
Thanks for informing me about the latest version, Curse notifications are not that great...
I was missing to add it on Modrinth.

Sounds good! Thanks.

**Comment by MisterPeModder** [comment]
Yeah, the mod download interface of curseforge leaves a lot to be desired, although it is my fault for not checking with an older version of cloth-config.
